### PR TITLE
Dense Bees

### PR DESCRIPTION
**Pull request by Pdiddy973**
very WIP much to do

### CODE REVIEW

**Comment by ladylexxie** [comment]
thicc bee when

**Comment by Pdiddy973** [comment]
when i get compreseed metal blocks ^^

**Comment by ladylexxie** [comment]
damn that was a fast response

**Comment by Pdiddy973** [comment]
~~makes a mod to make more bees~~
Time to actually make densey bois

**Comment by Pdiddy973** [comment]
just need to make "Beediddy" to make all of the dense bees

**Review by ladylexxie — DISMISSED** [review]
Dont forget about conflicts

**Review by ladylexxie — APPROVED** [review]

**Pull request merged**
