### PR TITLE
Make salvager great again!

### PR DESCRIPTION
**Pull request by WhitePhant0m**
I had earlier effectively disabled the SGear salvager when changing configs for it, I used the wrong values for it, and now I'll fix it.

### CODE REVIEW

**Review by Letoric — APPROVED** [review]
It's about time! :P
Don't forget to tag the issue so we can close it.

**Comment by lucasvanhalst** [comment]
There's also a comment about it here, looks like you forgot to remove the comment:

https://github.com/AllTheMods/ATM-6/blob/master/kubejs/client_scripts/jei.js#L9

**Comment by WhitePhant0m** [comment]
> 
> 
> There's also a comment about it here, looks like you forgot to remove the comment:
> 
> https://github.com/AllTheMods/ATM-6/blob/master/kubejs/client_scripts/jei.js#L9

you are looking at the master branch, it's already removed on staging, master branch is for releases

**Comment by Letoric** [comment]
Thanks. That's not the correct branch to look at.

**Pull request merged**
