### PR TITLE
Add some Chinese localization

### PR DESCRIPTION
**Pull request by ZHAY10086**

### CODE REVIEW

**Comment by thevortex** [comment]
i like the look of this :) we should be putting this to the staging branch tho correct @jeremiahwinsley ?

**Comment by ZHAY10086** [comment]
Thanks for reply. BTW, does `Uru` have any exact meaning?

**Comment by jeremiahwinsley** [comment]
Uru is a reference to Marvel - https://marvel.fandom.com/wiki/Uru

**Comment by ZHAY10086** [comment]
Thanks a lot!

**Review by jeremiahwinsley — APPROVED** [review]

**Pull request merged**
