### PR TITLE
Update astralsorcery.toml

### LINKED ISSUE #671: Astral Sorcery Mineralis Ritual produces "Other" Ores
**Describe the bug**
When using the mineralis ritual from Astral Sorcery, it seems to spawn equal amounts of normal and "other" ores.

**To Reproduce**
1. Create a mineralis attuned crystal
2. Place the crystal in a ritual pedestal
3. Place stone around the perimeter of the pedestal
4. Observe as "other" ores are created.

**Expected behavior**
Only normal ores should be produced by the ritual.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ChosunOne**
Add "alltheores" to the mod blacklist to prevent spawning in "other" ores.

Should hopefully fix #671

### CODE REVIEW

**Comment by ChosunOne** [comment]
Would be too general, since ores get unified into "alltheores"

**Comment by thevortex** [comment]
issue will be corrected in the next update of alltheores, tags are being juggled about so this wont happen going forwards

**Comment by GreyMario** [comment]
Incidentally, having happened across this issue with the Stone Enrichment perk, what's the harvest level required for Other ores? My diamond tools refuse to care about them in the slightest, and my darkroom is now infested with these seemingly unbreakable ores.

**Comment by thevortex** [comment]
level 6-7 depending on the ore so vibranium or unobtainium tools required

**Comment by GreyMario** [comment]
_Ah, yikes._ That makes spawning it via Stone Enrichment, Mineralis ritual, or Orechid incredibly problematic, then.

**Comment by Ruchian** [comment]
Read the changelog: https://www.curseforge.com/minecraft/mc-mods/astral-sorcery/files

` - Several configuration options got adjusted; unless it's critically needed, please consider regenerating the config files or double check existing configurations; Mainly aevitas mantle configuration and tile acceleration registry`

As such make sure you have the new default before editting the config.

**Pull request closed without merging**
