### PR TITLE
Update cloche.js

### PR DESCRIPTION
**Pull request by desagas**
Having inferium in two places (top, here, and the 7 different soils at the bottom) prevents the recipes of other tiers of farm land from working inside of the cloches, which means that currently, 1.8.9, cloches only produce 2 inferium essence regardless of what farmland is inside or the cloche.

This change fixes this, so that inferium now produces as is listed in JEI, and what is at the bottom of this script.

### CODE REVIEW

**Comment by jeremiahwinsley** [comment]
I tested this in world and the various soils output 1, 2, 2, 3, 3, 4 respectively, not 2-7. So I think we'll just remove those to fix the JEI quantity, and then possibly increase that in a future update. Thanks for the PR though!

**Comment by desagas** [comment]
Oh, strange, because in my world, the soils output respectively as the script mentions, 1-7, with my proposed change, and 2 for every single soil level otherwise ... I wonder what would be causing it to work differently on different machines? Well, at least you know about it, that is the main point. Thanks.

**Comment by jeremiahwinsley** [comment]
in the cloche it would yes, but it doesn't do that when planting the seeds on farmland in the world.

**Comment by desagas** [comment]
Absolutely. That is what the post was all about, the garden cloche, nothing else. Jei is incorrect with the way your script is setup, as priority is given to the first record, and will ignore further iterations of the same outputs. Sadly, a drawback to Kubjs.

**Comment by desagas** [comment]
In your current script, the garden cloches output 2 essense, regardless of whatever farmland your put inside of it, yet, your script, you have added 2-7 respectively for the level of farmland ... that is what I was pointing out, nothing in world at all. Lol.

**Comment by jeremiahwinsley** [comment]
correct, what I meant was that the desired behavior here would be either matching the in world amount (including in other things like botany pots) or returning a smaller, static amount (like it does now).

**Pull request closed without merging**
